### ISSUE TITLE
After some time, Frontify shows an API access token expired message

### ISSUE THREAD

**Issue by macolo** [lab360-ch/django-frontify#1]
- After some time, Frontify shows a token expired message
- The user then has to clear the website's application cache as described here to make it work again: https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome/

![image](https://user-images.githubusercontent.com/4056979/108732110-888f4180-752d-11eb-9429-333d69a88d14.png)

**Comment by lab360-ch** [comment]
Hi @macolo 

The issues should be fixed in version 0.1.1
This is the first version on pypi.org

Best regards

Ralf
