### ISSUE TITLE
Frontify doesn't allow to download PDF

### ISSUE THREAD

**Issue by vnosov93** [lab360-ch/django-frontify#2]
I found out that the Frontify integration doesn't let us see URLs for PDF files. It returns only the URL to an image preview of the first page of the PDF.

I would like to have the ability to get URLs for pdf files.

In addition to that, I found out that download_url is empty for pdf files. Images such as png, jpeg, and jpg have a link.

Would you be able to help?

**Comment by lab360-ch** [comment]
Hi @vnosov93 

I can't reproduce the issue. I Tested it with my Test Account and I get the download_url from Frontify.
Maybe this would be an issue on your Frontify Account and not within this plugin.
Please contact Frontify for this issue.

Best regards

Ralf
